# Generated by Django 4.2 on 2023-05-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Tienda')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CategoriaProd',
                'verbose_name_plural': 'CategoriasProd',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Tienda')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='Tienda')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='Tienda')),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.FloatField(max_length=20)),
                ('precio_oferta', models.FloatField(max_length=20)),
                ('created', models.BooleanField(default=True)),
                ('updated', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
